# Generated by Django 3.2.25 on 2024-11-26 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='lat',
            field=models.DecimalField(decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='lon',
            field=models.DecimalField(decimal_places=5, max_digits=10, null=True),
        ),
    ]
