# Generated by Django 3.2.25 on 2024-10-13 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='fecha_creación',
            field=models.DateField(default='2024-10-13'),
        ),
    ]
