# Generated by Django 5.1.2 on 2024-10-14 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_alter_tarea_fecha_creación'),
        ('todoapp', '0002_auto_20241013_1823'),
    ]

    operations = [
    ]
