# Generated by Django 3.2.25 on 2024-10-13 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
        ('todoapp', '0003_merge_20241013_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField()),
                ('description', models.TextField()),
                ('categorias', models.ManyToManyField(to='categorias.Categoria')),
            ],
        ),
    ]
