# Generated by Django 3.2.25 on 2024-10-14 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_merge_20241013_2124'),
        ('todoapp', '0004_restaurant'),
    ]

    operations = [
    ]
