# Generated by Django 3.2.25 on 2024-10-14 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comunas', '0001_initial'),
        ('todoapp', '0006_auto_20241014_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='comuna',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='comunas.comuna'),
            preserve_default=False,
        ),
    ]
