# Generated by Django 3.2.25 on 2024-11-21 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0009_alter_tarea_fecha_creación'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pronombre',
        ),
        migrations.AddField(
            model_name='user',
            name='tipo',
            field=models.CharField(choices=[('Cliente', 'Cliente'), ('Propietario', 'Propietario')], default='Cliente', max_length=12),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Tarea',
        ),
    ]
